sudo: required
language: generic
services:
  - docker
  
before_install:
  - docker build -t franzbewerunge/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true franzbewerunge/docker-react npm run test