sudo: required
services:
  - docker
  
before_install:
  - docker build -t franzbewerunge/docker-react -f Dockerfile.dev .

script:
  - docker run franzbewerunge/docker-react npm run test -- --coverage